import { chromium } from 'playwright';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 }, deviceScaleFactor: 1 });
const page = await ctx.newPage();
await page.goto('http://127.0.0.1:4173', { waitUntil: 'networkidle' });
await page.waitForTimeout(500);
const proj = page.locator('[data-action="open-project"]').first();
if (await proj.count()) await proj.click();
await page.waitForTimeout(400);
const navBtn = page.locator('text=剧情开发').first();
if (await navBtn.count()) await navBtn.click();
await page.waitForTimeout(800);
await page.screenshot({ path: 'tests/e2e/realcheck-shots/_plots-after-full.png', fullPage: false });
await browser.close();
